#!/bin/bash
pushd ~/github.com/josd/josd.github.io/temp/eye-wasm
node swipl-wasm/home/swipl.js -f eye.pl -g main -- --nope socrates.n3 --query socrates-query.n3
node swipl-wasm/home/swipl.js -f eye.pl -g main -- --nope gps-plugin.n3 gps-example1.n3 --query gps-query1.n3
node swipl-wasm/home/swipl.js -f eye.pl -g main -- --nope test-dt1.n3 test-dt2.n3 test-facts.n3 --query test-query.n3
node swipl-wasm/home/swipl.js -g run,halt webeye.pl dt.pl
node swipl-wasm/home/swipl.js -g run,halt webeye.pl sdcoding.pl
popd
