% Deep taxonomy
% See http://ruleml.org/WellnessRules/files/WellnessRulesN3-2009-11-10.pdf

'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'('https://josd.github.io/ns#z','https://josd.github.io/ns#N0').
'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'(A,C) :- 'http://www.w3.org/2000/01/rdf-schema#subClassOf'(B,C),'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'(A,B).

'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N0','https://josd.github.io/ns#N1').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N0','https://josd.github.io/ns#I1').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N0','https://josd.github.io/ns#J1').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N1','https://josd.github.io/ns#N2').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N1','https://josd.github.io/ns#I2').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N1','https://josd.github.io/ns#J2').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N2','https://josd.github.io/ns#N3').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N2','https://josd.github.io/ns#I3').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N2','https://josd.github.io/ns#J3').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N3','https://josd.github.io/ns#N4').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N3','https://josd.github.io/ns#I4').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N3','https://josd.github.io/ns#J4').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N4','https://josd.github.io/ns#N5').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N4','https://josd.github.io/ns#I5').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N4','https://josd.github.io/ns#J5').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N5','https://josd.github.io/ns#N6').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N5','https://josd.github.io/ns#I6').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N5','https://josd.github.io/ns#J6').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N6','https://josd.github.io/ns#N7').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N6','https://josd.github.io/ns#I7').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N6','https://josd.github.io/ns#J7').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N7','https://josd.github.io/ns#N8').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N7','https://josd.github.io/ns#I8').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N7','https://josd.github.io/ns#J8').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N8','https://josd.github.io/ns#N9').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N8','https://josd.github.io/ns#I9').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N8','https://josd.github.io/ns#J9').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N9','https://josd.github.io/ns#N10').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N9','https://josd.github.io/ns#I10').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N9','https://josd.github.io/ns#J10').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N10','https://josd.github.io/ns#N11').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N10','https://josd.github.io/ns#I11').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N10','https://josd.github.io/ns#J11').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N11','https://josd.github.io/ns#N12').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N11','https://josd.github.io/ns#I12').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N11','https://josd.github.io/ns#J12').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N12','https://josd.github.io/ns#N13').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N12','https://josd.github.io/ns#I13').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N12','https://josd.github.io/ns#J13').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N13','https://josd.github.io/ns#N14').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N13','https://josd.github.io/ns#I14').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N13','https://josd.github.io/ns#J14').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N14','https://josd.github.io/ns#N15').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N14','https://josd.github.io/ns#I15').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N14','https://josd.github.io/ns#J15').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N15','https://josd.github.io/ns#N16').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N15','https://josd.github.io/ns#I16').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N15','https://josd.github.io/ns#J16').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N16','https://josd.github.io/ns#N17').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N16','https://josd.github.io/ns#I17').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N16','https://josd.github.io/ns#J17').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N17','https://josd.github.io/ns#N18').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N17','https://josd.github.io/ns#I18').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N17','https://josd.github.io/ns#J18').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N18','https://josd.github.io/ns#N19').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N18','https://josd.github.io/ns#I19').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N18','https://josd.github.io/ns#J19').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N19','https://josd.github.io/ns#N20').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N19','https://josd.github.io/ns#I20').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N19','https://josd.github.io/ns#J20').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N20','https://josd.github.io/ns#N21').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N20','https://josd.github.io/ns#I21').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N20','https://josd.github.io/ns#J21').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N21','https://josd.github.io/ns#N22').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N21','https://josd.github.io/ns#I22').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N21','https://josd.github.io/ns#J22').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N22','https://josd.github.io/ns#N23').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N22','https://josd.github.io/ns#I23').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N22','https://josd.github.io/ns#J23').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N23','https://josd.github.io/ns#N24').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N23','https://josd.github.io/ns#I24').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N23','https://josd.github.io/ns#J24').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N24','https://josd.github.io/ns#N25').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N24','https://josd.github.io/ns#I25').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N24','https://josd.github.io/ns#J25').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N25','https://josd.github.io/ns#N26').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N25','https://josd.github.io/ns#I26').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N25','https://josd.github.io/ns#J26').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N26','https://josd.github.io/ns#N27').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N26','https://josd.github.io/ns#I27').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N26','https://josd.github.io/ns#J27').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N27','https://josd.github.io/ns#N28').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N27','https://josd.github.io/ns#I28').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N27','https://josd.github.io/ns#J28').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N28','https://josd.github.io/ns#N29').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N28','https://josd.github.io/ns#I29').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N28','https://josd.github.io/ns#J29').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N29','https://josd.github.io/ns#N30').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N29','https://josd.github.io/ns#I30').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N29','https://josd.github.io/ns#J30').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N30','https://josd.github.io/ns#N31').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N30','https://josd.github.io/ns#I31').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N30','https://josd.github.io/ns#J31').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N31','https://josd.github.io/ns#N32').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N31','https://josd.github.io/ns#I32').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N31','https://josd.github.io/ns#J32').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N32','https://josd.github.io/ns#N33').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N32','https://josd.github.io/ns#I33').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N32','https://josd.github.io/ns#J33').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N33','https://josd.github.io/ns#N34').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N33','https://josd.github.io/ns#I34').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N33','https://josd.github.io/ns#J34').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N34','https://josd.github.io/ns#N35').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N34','https://josd.github.io/ns#I35').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N34','https://josd.github.io/ns#J35').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N35','https://josd.github.io/ns#N36').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N35','https://josd.github.io/ns#I36').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N35','https://josd.github.io/ns#J36').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N36','https://josd.github.io/ns#N37').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N36','https://josd.github.io/ns#I37').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N36','https://josd.github.io/ns#J37').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N37','https://josd.github.io/ns#N38').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N37','https://josd.github.io/ns#I38').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N37','https://josd.github.io/ns#J38').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N38','https://josd.github.io/ns#N39').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N38','https://josd.github.io/ns#I39').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N38','https://josd.github.io/ns#J39').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N39','https://josd.github.io/ns#N40').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N39','https://josd.github.io/ns#I40').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N39','https://josd.github.io/ns#J40').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N40','https://josd.github.io/ns#N41').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N40','https://josd.github.io/ns#I41').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N40','https://josd.github.io/ns#J41').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N41','https://josd.github.io/ns#N42').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N41','https://josd.github.io/ns#I42').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N41','https://josd.github.io/ns#J42').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N42','https://josd.github.io/ns#N43').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N42','https://josd.github.io/ns#I43').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N42','https://josd.github.io/ns#J43').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N43','https://josd.github.io/ns#N44').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N43','https://josd.github.io/ns#I44').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N43','https://josd.github.io/ns#J44').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N44','https://josd.github.io/ns#N45').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N44','https://josd.github.io/ns#I45').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N44','https://josd.github.io/ns#J45').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N45','https://josd.github.io/ns#N46').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N45','https://josd.github.io/ns#I46').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N45','https://josd.github.io/ns#J46').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N46','https://josd.github.io/ns#N47').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N46','https://josd.github.io/ns#I47').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N46','https://josd.github.io/ns#J47').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N47','https://josd.github.io/ns#N48').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N47','https://josd.github.io/ns#I48').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N47','https://josd.github.io/ns#J48').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N48','https://josd.github.io/ns#N49').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N48','https://josd.github.io/ns#I49').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N48','https://josd.github.io/ns#J49').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N49','https://josd.github.io/ns#N50').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N49','https://josd.github.io/ns#I50').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N49','https://josd.github.io/ns#J50').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N50','https://josd.github.io/ns#N51').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N50','https://josd.github.io/ns#I51').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N50','https://josd.github.io/ns#J51').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N51','https://josd.github.io/ns#N52').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N51','https://josd.github.io/ns#I52').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N51','https://josd.github.io/ns#J52').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N52','https://josd.github.io/ns#N53').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N52','https://josd.github.io/ns#I53').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N52','https://josd.github.io/ns#J53').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N53','https://josd.github.io/ns#N54').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N53','https://josd.github.io/ns#I54').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N53','https://josd.github.io/ns#J54').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N54','https://josd.github.io/ns#N55').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N54','https://josd.github.io/ns#I55').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N54','https://josd.github.io/ns#J55').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N55','https://josd.github.io/ns#N56').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N55','https://josd.github.io/ns#I56').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N55','https://josd.github.io/ns#J56').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N56','https://josd.github.io/ns#N57').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N56','https://josd.github.io/ns#I57').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N56','https://josd.github.io/ns#J57').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N57','https://josd.github.io/ns#N58').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N57','https://josd.github.io/ns#I58').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N57','https://josd.github.io/ns#J58').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N58','https://josd.github.io/ns#N59').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N58','https://josd.github.io/ns#I59').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N58','https://josd.github.io/ns#J59').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N59','https://josd.github.io/ns#N60').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N59','https://josd.github.io/ns#I60').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N59','https://josd.github.io/ns#J60').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N60','https://josd.github.io/ns#N61').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N60','https://josd.github.io/ns#I61').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N60','https://josd.github.io/ns#J61').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N61','https://josd.github.io/ns#N62').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N61','https://josd.github.io/ns#I62').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N61','https://josd.github.io/ns#J62').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N62','https://josd.github.io/ns#N63').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N62','https://josd.github.io/ns#I63').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N62','https://josd.github.io/ns#J63').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N63','https://josd.github.io/ns#N64').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N63','https://josd.github.io/ns#I64').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N63','https://josd.github.io/ns#J64').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N64','https://josd.github.io/ns#N65').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N64','https://josd.github.io/ns#I65').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N64','https://josd.github.io/ns#J65').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N65','https://josd.github.io/ns#N66').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N65','https://josd.github.io/ns#I66').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N65','https://josd.github.io/ns#J66').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N66','https://josd.github.io/ns#N67').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N66','https://josd.github.io/ns#I67').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N66','https://josd.github.io/ns#J67').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N67','https://josd.github.io/ns#N68').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N67','https://josd.github.io/ns#I68').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N67','https://josd.github.io/ns#J68').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N68','https://josd.github.io/ns#N69').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N68','https://josd.github.io/ns#I69').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N68','https://josd.github.io/ns#J69').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N69','https://josd.github.io/ns#N70').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N69','https://josd.github.io/ns#I70').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N69','https://josd.github.io/ns#J70').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N70','https://josd.github.io/ns#N71').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N70','https://josd.github.io/ns#I71').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N70','https://josd.github.io/ns#J71').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N71','https://josd.github.io/ns#N72').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N71','https://josd.github.io/ns#I72').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N71','https://josd.github.io/ns#J72').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N72','https://josd.github.io/ns#N73').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N72','https://josd.github.io/ns#I73').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N72','https://josd.github.io/ns#J73').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N73','https://josd.github.io/ns#N74').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N73','https://josd.github.io/ns#I74').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N73','https://josd.github.io/ns#J74').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N74','https://josd.github.io/ns#N75').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N74','https://josd.github.io/ns#I75').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N74','https://josd.github.io/ns#J75').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N75','https://josd.github.io/ns#N76').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N75','https://josd.github.io/ns#I76').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N75','https://josd.github.io/ns#J76').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N76','https://josd.github.io/ns#N77').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N76','https://josd.github.io/ns#I77').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N76','https://josd.github.io/ns#J77').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N77','https://josd.github.io/ns#N78').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N77','https://josd.github.io/ns#I78').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N77','https://josd.github.io/ns#J78').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N78','https://josd.github.io/ns#N79').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N78','https://josd.github.io/ns#I79').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N78','https://josd.github.io/ns#J79').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N79','https://josd.github.io/ns#N80').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N79','https://josd.github.io/ns#I80').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N79','https://josd.github.io/ns#J80').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N80','https://josd.github.io/ns#N81').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N80','https://josd.github.io/ns#I81').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N80','https://josd.github.io/ns#J81').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N81','https://josd.github.io/ns#N82').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N81','https://josd.github.io/ns#I82').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N81','https://josd.github.io/ns#J82').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N82','https://josd.github.io/ns#N83').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N82','https://josd.github.io/ns#I83').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N82','https://josd.github.io/ns#J83').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N83','https://josd.github.io/ns#N84').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N83','https://josd.github.io/ns#I84').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N83','https://josd.github.io/ns#J84').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N84','https://josd.github.io/ns#N85').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N84','https://josd.github.io/ns#I85').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N84','https://josd.github.io/ns#J85').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N85','https://josd.github.io/ns#N86').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N85','https://josd.github.io/ns#I86').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N85','https://josd.github.io/ns#J86').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N86','https://josd.github.io/ns#N87').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N86','https://josd.github.io/ns#I87').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N86','https://josd.github.io/ns#J87').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N87','https://josd.github.io/ns#N88').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N87','https://josd.github.io/ns#I88').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N87','https://josd.github.io/ns#J88').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N88','https://josd.github.io/ns#N89').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N88','https://josd.github.io/ns#I89').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N88','https://josd.github.io/ns#J89').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N89','https://josd.github.io/ns#N90').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N89','https://josd.github.io/ns#I90').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N89','https://josd.github.io/ns#J90').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N90','https://josd.github.io/ns#N91').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N90','https://josd.github.io/ns#I91').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N90','https://josd.github.io/ns#J91').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N91','https://josd.github.io/ns#N92').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N91','https://josd.github.io/ns#I92').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N91','https://josd.github.io/ns#J92').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N92','https://josd.github.io/ns#N93').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N92','https://josd.github.io/ns#I93').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N92','https://josd.github.io/ns#J93').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N93','https://josd.github.io/ns#N94').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N93','https://josd.github.io/ns#I94').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N93','https://josd.github.io/ns#J94').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N94','https://josd.github.io/ns#N95').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N94','https://josd.github.io/ns#I95').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N94','https://josd.github.io/ns#J95').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N95','https://josd.github.io/ns#N96').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N95','https://josd.github.io/ns#I96').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N95','https://josd.github.io/ns#J96').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N96','https://josd.github.io/ns#N97').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N96','https://josd.github.io/ns#I97').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N96','https://josd.github.io/ns#J97').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N97','https://josd.github.io/ns#N98').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N97','https://josd.github.io/ns#I98').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N97','https://josd.github.io/ns#J98').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N98','https://josd.github.io/ns#N99').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N98','https://josd.github.io/ns#I99').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N98','https://josd.github.io/ns#J99').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N99','https://josd.github.io/ns#N100').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N99','https://josd.github.io/ns#I100').
'http://www.w3.org/2000/01/rdf-schema#subClassOf'('https://josd.github.io/ns#N99','https://josd.github.io/ns#J100').

run :- 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'('https://josd.github.io/ns#z','https://josd.github.io/ns#N100'),write(true),nl.
