% Generating deep taxonomy

run :-
    open('edt.html',write,Out),
    write(Out,'<!DOCTYPE html>\n'),
    write(Out,'<html>\n'),
    write(Out,'    <head>\n'),
    write(Out,'        <title>eyebrow</title>\n'),
    write(Out,'    </head>\n'),
    write(Out,'    <body>\n'),
    write(Out,'        <script type="text/javascript" src="../modules/core.js"></script>\n'),
    write(Out,'        <script>\n'),
    write(Out,'var session = pl.create();\n'),
    write(Out,'\n'),
    write(Out,'var knows = `\n'),
    write(Out,'% Deep taxonomy\n'),
    write(Out,'% See http://ruleml.org/WellnessRules/files/WellnessRulesN3-2009-11-10.pdf\n'),
    write(Out,'\n'),
    (   between(0,100000,I),
        format(Out,"'http://example.org/ns#N0'('http://example.org/ns#i~d').~n",[I]),
        fail
    ;   true
    ),
    format(Out,"~n",[]),
    (   between(0,99999,I),
        J is I+1,
        format(Out,"'http://example.org/ns#N~d'(X) :- 'http://example.org/ns#N~d'(X).~n",[J,I]),
        format(Out,"'http://example.org/ns#I~d'(X) :- 'http://example.org/ns#N~d'(X).~n",[J,I]),
        format(Out,"'http://example.org/ns#J~d'(X) :- 'http://example.org/ns#N~d'(X).~n",[J,I]),
        fail
    ;   true
    ),
    write(Out,'`;\n'),
    write(Out,'\n'),
    write(Out,'var query = `\n'),
    format(Out,"'http://example.org/ns#N100000'('http://example.org/ns#i100000').~n",[]),
    write(Out,'`;\n'),
    write(Out,'\n'),
    write(Out,'session.consult(knows, {\n'),
    write(Out,'    success: function() { /* Program loaded correctly */ },\n'),
    write(Out,'    error: function(err) { /* Error parsing program */ }\n'),
    write(Out,'});\n'),
    write(Out,'\n'),
    write(Out,'session.query(query, {\n'),
    write(Out,'    success: function(goal) { /* Goal loaded correctly */ },\n'),
    write(Out,'    error: function(err) { /* Error parsing goal */ }\n'),
    write(Out,'});\n'),
    write(Out,'\n'),
    write(Out,'session.answer({\n'),
    write(Out,'    success: function(answer) {\n'),
    write(Out,'        document.write("<h2>Running ", location.pathname.split("/").slice(-1), "</h2>");\n'),
    write(Out,'        document.write("Query = ", query, "<br/><br/>");\n'),
    write(Out,'        document.write(session.format_answer(answer, {quoted: true}));\n'),
    write(Out,'    },\n'),
    write(Out,'    fail: function() { /* No more answers */ },\n'),
    write(Out,'    error: function(err) { /* Uncaught exception */ },\n'),
    write(Out,'    limit: function() { /* Limit exceeded */ }\n'),
    write(Out,'});\n'),
    write(Out,'        </script>\n'),
    write(Out,'    </body>\n'),
    write(Out,'</html>\n'),
    close(Out).
