#!/bin/bash
pushd ~/github.com/josd/josd.github.io
riot --base=https://josd.github.io/card.ttl --output=RDF/XML card.ttl > card.rdf
riot --base=https://josd.github.io/card.ttl --output=N-Triples card.ttl > card.nt
popd
