#!/bin/bash
pushd ~/github.com/eyereasoner/eye-js > /dev/null
git pull
npm run eye:update
npm i # To clone the updated version of eye
npm run build
#npx jest __tests__/all-test.ts
ts-node __tests__/no-jest.ts
popd > /dev/null
