#!/bin/bash
pushd ~/github.com/eyereasoner/see-lingua > /dev/null
swipl -f see.pl -g "qsave_program('see.pvm', [goal(main)]), halt."
popd > /dev/null
pushd ~/github.com/eyereasoner/see-lingua/lingua > /dev/null
./test
popd > /dev/null
