#!/bin/bash
pushd ~/github.com/josd/josd.github.io/temp/python > /dev/null
./test
git diff
echo ""
popd > /dev/null

pushd ~/github.com/josd/josd.github.io/temp/eye.py > /dev/null
./test
git diff
popd > /dev/null
