#!/bin/bash
pushd ~/github.com/mthom/scryer-prolog
git pull --all
cargo check --release
cargo build --release
cargo test --release
popd
pushd ~/github.com/josd/josd.github.io/temp/webeye
./test-scryer
git diff
popd
