#!/bin/bash
pushd ~/github.com/mthom/scryer-prolog > /dev/null
git pull
cargo build --release
cargo test --release
echo ""
popd > /dev/null
pushd ~/github.com/KNowledgeOnWebScale/retina > /dev/null
./test
git diff
popd > /dev/null
