#!/bin/bash
pushd ~/github.com/mthom/scryer-prolog
git pull --all
cargo check --release
cargo build --release
cargo test --release
popd
pushd ~/github.com/IDLabResearch/Webeye
./test-scryer
git diff
popd
