#!/bin/bash
pushd ~/github.com/mthom/scryer-prolog
git checkout ${1:-rebis-dev}
git pull
cargo build --release
cargo test --release
popd
pushd ~/github.com/josd/eye/reasoning/heisenberg
./prepare scryer-prolog
git diff
popd
