#!/bin/bash
pushd ~/github.com/mthom/scryer-prolog > /dev/null
git pull
cargo build --release
#cargo test --release
popd > /dev/null
echo ""

pushd ~/github.com/KNowledgeOnWebScale/eyelet > /dev/null
./test-scryer
popd > /dev/null
