#!/bin/bash
: '
pushd ~
mkdir wasm
cd wasm
git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
./emsdk install latest
./emsdk activate latest
cd ~/wasm
wget https://zlib.net/zlib-1.2.12.tar.gz
tar xf zlib-1.2.12.tar.gz
cd zlib-1.2.12/
source ../emsdk/emsdk_env.sh 
emconfigure ./configure
emmake make
cd ~/wasm
wget https://gmplib.org/download/gmp/gmp-6.2.1.tar.lz
tar xf gmp-6.2.1.tar.lz
cd gmp-6.2.1
emconfigure ./configure --host=none --disable-assembly --prefix=${HOME}/wasm
make -j
make install
popd
'
export CTEST_OUTPUT_ON_FAILURE=y
pushd ~/github.com/SWI-Prolog/swipl-devel
git pull
git submodule update
mkdir -p build.wasm
cd build.wasm
WASM_HOME=$HOME/wasm
source $WASM_HOME/emsdk/emsdk_env.sh
TOOLCHAIN=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
[ -f $TOOLCHAIN ] || echo "Could not find emscripten toolchain"
cmake -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN \
    -DCMAKE_BUILD_TYPE=Release \
    -DZLIB_LIBRARY=$WASM_HOME/zlib-1.2.12/libz.a \
    -DZLIB_INCLUDE_DIR=$WASM_HOME/zlib-1.2.12 \
    -DGMP_ROOT=$HOME/wasm \
    -DINSTALL_DOCUMENTATION=OFF \
    -G Ninja ..

rm -rf src/wasm-preload && ninja
popd
pushd ~/github.com/josd/eyebrow
rsync -azv ~/github.com/SWI-Prolog/swipl-devel/build.wasm/src/swipl-web.js swipl-web.js
rsync -azv ~/github.com/SWI-Prolog/swipl-devel/build.wasm/src/swipl-web.wasm swipl-web.wasm
rsync -azv ~/github.com/SWI-Prolog/swipl-devel/build.wasm/src/swipl-web.data swipl-web.data
git diff
popd
