#!/bin/bash
pushd ~/github.com/tau-prolog/tau-prolog > /dev/null
git pull
echo ""
popd > /dev/null

pushd ~/github.com/KNowledgeOnWebScale/brow > /dev/null
rsync -azv ~/github.com/tau-prolog/tau-prolog/modules .
./test
git diff
popd > /dev/null
