#!/bin/bash
pushd ~/github.com/trealla-prolog/trealla > /dev/null
git pull --all
make
#make test
echo ""
popd > /dev/null
pushd ~/github.com/eyereasoner/see/cases > /dev/null
./test tpl
popd > /dev/null
