#!/bin/bash
pushd ~/github.com/trealla-prolog/trealla > /dev/null
git pull --all
make
#make test
popd > /dev/null
echo ""

pushd ~/github.com/eyereasoner/eye/eyelet-prolog > /dev/null
./test-trealla
popd > /dev/null
