#!/bin/bash
pushd ~/github.com/trealla-prolog/trealla > /dev/null
git pull --all
make
make test
echo ""
popd > /dev/null
pushd ~/github.com/KNowledgeOnWebScale/phy > /dev/null
./test
git diff
popd > /dev/null
