#!/bin/bash
pushd ~/github.com/eyereasoner/eye; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/eye-js; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/Koreografeye; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/Notation3-By-Example; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/ph2; git pull --all; popd
echo ""
pushd ~/github.com/josd/josd.github.io; git pull --all; popd
echo ""
pushd ~/github.com/MellonScholarlyCommunication/Latar; git pull --all; popd
echo ""
pushd ~/github.com/SWI-Prolog/swipl-devel; git pull --all; popd
echo ""
pushd ~/github.com/w3c/N3; git pull --all; popd
echo ""
pushd ~/github.com/w3c-cg/rdfsurfaces; git pull --all; popd
echo ""
