#!/bin/bash
pushd ~/github.com/Dexagod/RDF-surfaces-reasoning; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/eye; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/eyebrow; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/EyeClient; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/EyeEarl; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/eye.js; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/EyeServer; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/Koreografeye; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/lib-rdfs; git pull --all; popd
echo ""
pushd ~/github.com/eyereasoner/Notation3-By-Example; git pull --all; popd
echo ""
pushd ~/github.com/inrupt/eye-js; git pull --all; popd
echo ""
pushd ~/github.com/josd/brow; git pull --all; popd
echo ""
pushd ~/github.com/josd/glass; git pull --all; popd
echo ""
pushd ~/github.com/josd/josd.github.io; git pull --all; popd
echo ""
pushd ~/github.com/josd/retina; git pull --all; popd
echo ""
pushd ~/github.com/josd/surface; git pull --all; popd
echo ""
pushd ~/github.com/MellonScholarlyCommunication/MiniOrchestrator; git pull --all; popd
echo ""
pushd ~/github.com/mthom/scryer-prolog; git pull --all; popd
echo ""
pushd ~/github.com/SWI-Prolog/swipl-devel; git pull --all; popd
echo ""
pushd ~/github.com/tau-prolog/tau-prolog; git pull --all; popd
echo ""
pushd ~/github.com/trealla-prolog/trealla; git pull --all; popd
echo ""
pushd ~/github.com/w3c/N3; git pull --all; popd
echo ""
pushd ~/github.com/w3c-cg/rdfsurfaces; git pull --all; popd
echo ""
